### ISSUE TITLE
Add "import modes" to support other mods

### ISSUE THREAD

**Issue by leovoel** [ultraabox/ultrabox_typescript#68]
Not every mod can be identified unambiguously when importing their song URL/JSON, so for better compatibility the user would need to specify what mod their song comes from.

To some degree, this can be detected automatically via the pasting of an entire URL (instead of just `#` and what comes after that), but there's nothing like this for JSON exports.

**Comment by MainCharacteroftheProblem** [comment]
Some of the things that need to be adjusted are:

Importing BeepBox songs causes every instrument to be 25 volume
Importing midis leads to the scale being Harmonic Minor instead of Free (though this is helpful in spotting midis)
EQ mod dot positions are lost on export
 
 (this list is from the closed issue)
